_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
actor_lr:
    value: 0.01
batch_size:
    value: 128
buffer_capacity:
    value: 1000
critic_lr:
    value: 0.01
env_name:
    value: simple_nav_v1
episode_length:
    value: 25
episode_num:
    value: 10000
gamma:
    value: 0.95
learn_interval:
    value: 100
random_steps:
    value: 5000
tau:
    value: 0.02
